language: python
python:
  - "3.5"
  - "3.6"
  - "pypy3"
  - "3.5-dev"
  - "3.6-dev"
env:
  BING_KEY: $BING_KEY
install: "pip install -r requirements.txt"
script: py.test
notifications:
  email: false
deploy:
  provider: pypi
  user: $PYPI_USER
  password:
    secure: $PYPI_PASSWORD
  on:
    branch: master
    python: '3.6'